name: Terraform PR Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write  # required for OIDC login to Azure

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_INPUT: false
      TF_CLI_ARGS_init: -no-color
      TF_CLI_ARGS_validate: -no-color
      TF_CLI_ARGS_plan: -no-color
      # Authenticate Terraform azurerm provider using Service Principal (JSON in AZURE_CREDENTIALS)
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      # Backend auth to Storage (access key). Alternatively, assign RBAC and omit this.
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      # Also log in az CLI for any az commands used during the job
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      # Run formatting first so it is independent of any cloud auth
      - name: Terraform Format
        run: terraform fmt -check -diff -recursive

      # Login to Azure (service principal JSON via AZURE_CREDENTIALS secret)
      - name: Setup Azure CLI & Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Initialize. If your backend requires extra settings, prefer setting them via secrets/environment vars rather than hardcoding.
      - name: Terraform Init
        run: terraform init -upgrade -backend-config="key=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" -backend-config="container_name=tfstate" -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"

      - name: Terraform Validate
        run: terraform validate

      # Create a plan. This will not apply changes, only compute the execution plan.
      - name: Terraform Plan
        run: terraform plan -input=false -lock=false -out=tfplan

      # Optionally, upload plan as an artifact for later review
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
